akka.http.cors {
  allowed-origins = ["*"]
  allowed-headers = ["Content-Type", "Authorization"]
}

akka.javasdk.agent {
  model-provider = googleai-gemini
  googleai-gemini {
    model-name = "gemini-2.5-flash"
    temperature = 0.0
    api-key = ${GEMINI_API_KEY}
  }
}

